"""init

Revision ID: 2c959be484b8
Revises:
Create Date: 2026-01-17 13:22:54.417334

"""

# Standard Library Packages
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2c959be484b8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
