"""removed description column from job_results table

Revision ID: 9518fefb81ff
Revises: fe308a5d4f58
Create Date: 2026-09-24 22:14:38.883592

"""

# Standard Library Packages
from typing import Sequence, Union

# Third Party Packages
import sqlalchemy as sa

# Local Project
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9518fefb81ff"
down_revision: Union[str, Sequence[str], None] = "fe308a5d4f58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_results", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_results", sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
