"""added index on 'job_id'

Revision ID: cc1c49f9aee1
Revises: 6899c6bba458
Create Date: 2026-01-19 13:24:40.224642

"""

# Standard Library Packages
from typing import Sequence, Union

# Local Project
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc1c49f9aee1"
down_revision: Union[str, Sequence[str], None] = "6899c6bba458"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_job_results_job_id"), "job_results", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_results_job_id"), table_name="job_results")
    # ### end Alembic commands ###
