"""Add new workflow_runs table

Revision ID: d1023561952d
Revises: cc1c49f9aee1
Create Date: 2026-02-22 14:14:20.613401

"""

# Standard Library Packages
from typing import Sequence, Union

# Third Party Packages
import sqlalchemy as sa

# Local Project
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1023561952d"
down_revision: Union[str, Sequence[str], None] = "cc1c49f9aee1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("job_results", sa.Column("workflow_id", sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, "job_results", "workflow_runs", ["workflow_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "job_results", type_="foreignkey")
    op.drop_column("job_results", "workflow_id")
    op.drop_table("workflow_runs")
    # ### end Alembic commands ###
