"""Added new 'completed' column in 'workflow_runs' table

Revision ID: fe308a5d4f58
Revises: d1023561952d
Create Date: 2026-02-22 14:40:37.216707

"""

# Standard Library Packages
from typing import Sequence, Union

# Third Party Packages
import sqlalchemy as sa

# Local Project
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe308a5d4f58"
down_revision: Union[str, Sequence[str], None] = "d1023561952d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_runs", sa.Column("completed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_runs", "completed")
    # ### end Alembic commands ###
